### ISSUE TITLE
Indicaciones por piezas a imprimir

### ISSUE THREAD

**Issue by fprietorossi** [FABINACAP/REDFAB_3DFDM#1]
Estimados.
Se encuentran las piezas imprimibles de la maquina, pero debería existir una pequeña descripción de requerimientos para cada una de ellas, por ejemplo, ubicación en la cama de impresión (para evitar que se rompa bajo tensión), nivel de relleno, cantidad de impresiones de cada pieza, etc.

**Comment by FABINACAP** [comment]
Estimado Francisco, muchas gracias por su comentario.
Estamos trabajando en la documentación necesaria para que el armado sea mas claro y preciso.
Se actualizo lista de archivos y  BOM donde se indica el total de componentes impresos y configuraciones recomendadas.
Saludos.

**Comment by fprietorossi** [comment]
Excelente, está desarrollándose muy bien
