### ISSUE TITLE
firmware

### ISSUE THREAD

**Issue by jaimereyesc** [FABINACAP/REDFAB_3DFDM#2]
hola, podrian subir los archivos de los firmware que instalamos en la capacitacion al final, cuando terminamos las maquinas. ya que las 2 que llegaron a mi sede (Maipú) venian con una version muy distinta a la que usamos y ademas descalibradas.
esto ya que lo mas probable es que no sea el unico al que le pase, y asi tener una forma de setearlas.

gracias

**Comment by FABINACAP** [comment]
Estimado Jaime.
FW para impresora se encuentra subido en el repositorio. 
En relación a la calibración, esto es algo que va a ocurrir siempre, es parte del proceso de aprendizaje y de mojara continua ;)
Saludos

**Comment by jaimereyesc** [comment]
gracias por subirla 
saludos

**Comment by fprietorossi** [comment]
Para poder compilar el firmware, se necesita tener en el equipo la librería U8glib_Arduino, la cual se puede descargar desde https://github.com/olikraus/U8glib_Arduino/releases

**Comment by fprietorossi** [comment]
Compila mejor usando el IDE de Arduino 1.9.0 BETA (Descarga en https://www.arduino.cc/download_handler.php)  para evitar el problema de error por nombre del archivo o extensión muy largo que aparece en la versión 1.8.x

**Comment by FABINACAP** [comment]
Si nadie mas tiene dudas por lo comentado.. se cierra este tema.
gracias Francisco por el aporte.-
