### ISSUE TITLE
Instrucciones de Armado de Piezas

### ISSUE THREAD

**Issue by fprietorossi** [FABINACAP/REDFAB_3DFDM#3]
Existe el esquema de las piezas que son cortadas para el armado de la máquina
Se agradecería un set de imágenes o indicativo para el armado de ellas, junto a que piezas impresas deben usarse

**Comment by FABINACAP** [comment]
Francisco... pronto subiremos el manual.
Saludos

**Comment by elisahonorato** [comment]
Hola! Al final subieron el manual?
