### ISSUE TITLE
Problema de tracción en filamento

### ISSUE THREAD

**Issue by vverav** [FABINACAP/REDFAB_3DFDM#4]
Estimados:
Tenemos un problema con la tracción del filamento, que "patina" al pasar por las ruedas que deberían impulsarlo al extrusor. La impresora funciona, pero al no poder jalar de manera suave el filamento por momentos comienza a depositar PLA de manera irregular (no líneas, sino que básicamente deja gotas intercaladas con zonas sin material o muy poco). 
Un video de cómo el filamento no puede ser impulsado puede ser visto aquí:

https://www.dropbox.com/s/ou4nkrbkag875vo/VID_20190305_161715.mp4?dl=0

Hasta el momento hemos chequeado el motor que lo impulsa y la pieza que se atacha a este (incluso armamos la misma pieza completa con las partes de otra impresora nueva, y el problema continuó), así como estamos seguros que la manguera de silicona efectivamente entra completamente en el extrusor, por lo que no hay roce dentro de este. Tampoco el filamento está trabado o es irregular de algún modo (hemos probado con al menos tres filamentos diferentes). La temperatura del extrusor es la correcta, y dado que por ratos imprime bien no creemos que haya una obstrucción en el cabezal.
Tenemos la duda si podría ser algo relacionado con la potencia del motor, y nos queda probar el montaje completo de un motor de filamento de otra impresora que esté operando correctamente. ¿Qué otras pruebas nos sugieren hacer?
Saludos

**Comment by FABINACAP** [comment]
Hola muchachos.. por lo que veo en el video, la perdida de pasos puede estar relacionada mas bien con obstrucción en el cabezal bowden. esto suele ocurrir por diferentes motivos. 
les recomiendo retirar el filamento del cabezal ver el estado, verificar que el tubo de teflón llegue correctamente. también revisar los pasos del extrusor.
suban mas imágenes del sistema completo .

https://www.spainlabs.com/foros/tema-GUIA-DEFINITIVA-de-impresion-3d-todos-tus-problemas-resueltos--5081

**Comment by vverav** [comment]
Probé si era una obstrucción en el cabezal, pero se me olvidó mencionar un detalle: el filamento resbala incluso cuando el filamento todavía no ha llegado al cabezal cuando se carga. De hecho he notado que si se modifica un poco la presión entre las dos ruedas que impulsan el filamento (se aliviana un poco) la tracción mejora. Seguiré haciendo pruebas para encontrar la causa.

**Comment by FABINACAP** [comment]
En base a lo comentado entonces, puede que sea la potencia entregada al motor PAP, recomiendo lo siguiente.
ajustar el potenciometro del pololu A4988. utilizar voltimetro.
una ves calibrado en un valor ref. 0.8-0.85v mover motor extrusor sin tubo de teflon puesto para ver como avanza el filamento.
Saludos

**Comment by fprietorossi** [comment]
> Hola muchachos.. por lo que veo en el video, la perdida de pasos puede estar relacionada mas bien con obstrucción en el cabezal bowden. esto suele ocurrir por diferentes motivos.
> les recomiendo retirar el filamento del cabezal ver el estado, verificar que el tubo de teflón llegue correctamente. también revisar los pasos del extrusor.
> suban mas imágenes del sistema completo .
> 
> https://www.spainlabs.com/foros/tema-GUIA-DEFINITIVA-de-impresion-3d-todos-tus-problemas-resueltos--5081

Es un excelente referente de los problemas la guia, podriamos hacernos una para nosotros, del mismo estilo, es decir:
- Problema típico
- Causal
- Posibilidades de solución

Saludos

**Comment by vverav** [comment]
> En base a lo comentado entonces, puede que sea la potencia entregada al motor PAP, recomiendo lo siguiente.
> ajustar el potenciometro del pololu A4988. utilizar voltimetro.
> una ves calibrado en un valor ref. 0.8-0.85v mover motor extrusor sin tubo de teflon puesto para ver como avanza el filamento.
> Saludos

Hola Chicos. Ajusté el potenciómetro (de 0.80 lo pasé a 0.85), pero sigue presentando el problema, aunque en esta ocasión no lo hizo cuando el filamento estaba en camino al cabezal, sino que una vez que llegó. Haré otras pruebas y veré cómo me va. Puedo montar el motor en otra impresora que está operando correctamente para confirmar/descartar que el problema sea en este elemento y no algo en la extrusión. Les contaré cómo me va...
