### ISSUE TITLE
Problema con calentamiento de cama / boquilla

### ISSUE THREAD

**Issue by vverav** [FABINACAP/REDFAB_3DFDM#5]
Estimados:
Tengo un problema con una de las impresoras, que ha estado sistemáticamente dando problemas de calentamiento de la cama. He probado si la placa envía la señal cuando se le da la orden de calentar (con la cama desconectada) y lo hace, pero al conectar los cables deja de enviar voltaje. Probé la cama que tenía instalada en otra impresora, y la calienta sin problemas, por lo que no está en corte, así como puse en la impresora con problemas una cama que estaba funcionando en otra máquina y el error continua (aunque en un principio funcionó algunas horas). El termistor está bueno, y repasé las conexiones por si había algo desoldado, pero no encontré nada. La luz testigo que tiene la RAMPS actúa según lo esperado, y no enciende cuando el calentamiento de la cama es fallido.
En un principio pensé que podía ser la RAMPS, que había perdido la salida de potencia, pero la cambié por una nueva y no hubo resultados. También pensé que podía ser un problema de la fuente al exigir más corriente, pero la boquilla si la calienta. Ahora, a la RAMPS llegan dos conexiones desde la fuente, pero me imagino que la fuente sólo tiene varios conectores por polo, pero no realmente salidas independientes.
En el caso de la cama, el mensaje es este:

![IMG_20190329_152957](https://user-images.githubusercontent.com/48357257/55254988-22fa8380-5238-11e9-8d7e-2c8a48f3cf0d.jpg)

En la misma máquina tuve un problema con el calentamiento de la boquilla, e hice pruebas similares, pero resultó que al parecer se había quemado el calefactor, pues al poner una nueva dejó de dar problemas (hasta ahora).
¿Qué más podría probar?

**Comment by FABINACAP** [comment]
Este problema se da basicamente por las condiciones ambientales (sistemas de aire acondicionado) por lo tanto recomiendo evitar de alguna manera circulaciones de aire.. esto es fundamental sobre todo para trabajar con materiales como el ABS.-
Saludos,
